apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: us-central1-docker.pkg.dev/celestial-baton-441615-q8/gig-space/api-gateway:latest
        ports:
        - containerPort: 8081
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: DSN
        - name: USER_CONN
          value: "user-svc-service:8080"
        - name: GIG_CONN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: GIG_SVC_URL
        - name: CHAT_CONN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: CHAT_SVC_URL
        - name: PAYMENT_CONN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: PAYMENT_SVC_URL
        - name: SEARCH_CONN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: SEARCH_SVC_URL
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: TOKEN_SECRET
      volumes:
      - name: env-volume
        secret:
          secretName: gig-space-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
