apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ashif-online-tls
  namespace: default
spec:
  secretName: ashif-online-tls
  dnsNames:
  - ashif.online 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
