apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
  labels:
    app: payment-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-svc
  template:
    metadata:
      labels:
        app: payment-svc
    spec:
      containers:
      - name: payment-svc
        image: us-central1-docker.pkg.dev/celestial-baton-441615-q8/gig-space/payment-svc:latest
        ports:
        - containerPort: 8084
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: DSN
        - name: PORT
          value: ":8084"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: RAPI_KEY
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: RAPI_SECRET
        - name: USER_CONN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: USER_SVC_URL
        - name: GIG_CONN
          valueFrom:
            secretKeyRef:
              name: gig-space-secret
              key: GIG_SVC_URL
      volumes:
      - name: env-volume
        secret:
          secretName: gig-space-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  labels:
    app: payment-svc
spec:
  selector:
    app: payment-svc
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: ClusterIP
