name: Build and Push Docker Images to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - Api_gateway
          - User_Svc
        region: [us-central1] # Adjust the region as needed

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ matrix.region }}-docker.pkg.dev

    - name: Set up .env file for service
      run: |
        case "${{ matrix.service }}" in
          Api_gateway)
            echo "${{ secrets.API_GATEWAY_CONFIG }}" > ./Api_gateway/.env
            ;;
          User_Svc)
            echo "${{ secrets.USER_SVC_CONFIG }}" > ./User_Svc/.env
            ;;
        esac

    - name: Build Docker Image
      run: |
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        docker build \
          -t ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gig-space/$SERVICE_NAME:latest \
          ./${{ matrix.service }}

    - name: Push Docker Image to Artifact Registry
      run: |
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        docker push ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gig-space/$SERVICE_NAME:latest
