name: Build and Push Docker Images to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [Api_gateway, User_svc] # List all your services
        region: [us-central1] # Region for Artifact Registry

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ matrix.region }}-docker.pkg.dev

    - name: Create .env file if secret exists
      run: |
        ENV_SECRET_NAME=$(echo "${{ matrix.service }}" | tr '[:lower:]' '[:upper:]')_CONFIG
        ENV_CONTENT=${{ secrets[ENV_SECRET_NAME] }}
        if [ -n "$ENV_CONTENT" ]; then
          echo "$ENV_CONTENT" > ./${{ matrix.service }}/.env
        else
          echo "No secret found for $ENV_SECRET_NAME, skipping .env creation."
        fi

    - name: Build Docker Image
      run: |
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        docker build \
          -t ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME-svc/$SERVICE_NAME:latest \
          ./${{ matrix.service }}

    - name: Push Docker Image to Artifact Registry
      run: |
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        docker push ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME-svc/$SERVICE_NAME:latest
