name: Build and Push All Services to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - Api_gateway
          - User_svc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Map Secrets to Environment Variables
      run: |
        if [ "${{ matrix.service }}" == "Api_gateway" ]; then
          echo "${{ secrets.Api_gateway_config }}" > .env
        elif [ "${{ matrix.service }}" == "User_svc" ]; then
          echo "${{ secrets.user_svc_config }}" > .env
        fi
      working-directory: ./${{ matrix.service }}

    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.service }}/svc:latest ./${{ matrix.service }}

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.service }}/svc:latest
