name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE_CONTENT }}" > ./Api_gateway/.env

    - name: Build Docker Image
      run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway-svc/api-gateway:latest ./Api_gateway

    - name: Push Docker Image to Artifact Registry
      run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-gateway-svc/api-gateway:latest
