name: Build, Push, and Deploy Docker Images to GCP Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - Api_gateway
          - User_Svc
          - Payment_Svc
          - Chat_Svc
          - Search_Svc
          - Gig_Svc
          - Notification_Svc
        region: [us-central1]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Add Google Cloud SDK repository and public key
        run: |
          # Add the Google Cloud SDK repository
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          
          # Download and add the public key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
          
          # Update package list
          sudo apt-get update

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Set up .env file for the selected service
        run: |
          case "${{ matrix.service }}" in
            Api_gateway)
              echo "${{ secrets.API_GATEWAY_CONFIG }}" > ./Api_gateway/.env
              ;;
            User_Svc)
              echo "${{ secrets.USER_SVC_CONFIG }}" > ./User_Svc/.env
              ;;
            Payment_Svc)
              echo "${{ secrets.PAYMENT_SVC_CONFIG }}" > ./Payment_Svc/.env
              ;;
            Chat_Svc)
              echo "${{ secrets.CHAT_SVC_CONFIG }}" > ./Chat_Svc/.env
              ;;
            Search_Svc)
              echo "${{ secrets.SEARCH_SVC_CONFIG }}" > ./Search_Svc/.env
              ;;
            Gig_Svc)
              echo "${{ secrets.GIG_SVC_CONFIG }}" > ./Gig_Svc/.env
              ;;
            Notification_Svc)
              echo "${{ secrets.NOTIFICATION_SVC_CONFIG }}" > ./Notification_Svc/.env
              ;;
            *)
              echo "No configuration found for ${{ matrix.service }}"
              exit 1
              ;;
          esac

      - name: Build Docker Image
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
          docker build \
            -t ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gig-space/$SERVICE_NAME:latest \
            ./${{ matrix.service }}

      - name: Push Docker Image to Artifact Registry
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
          docker push ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gig-space/$SERVICE_NAME:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials gig-space-cluster --region ${{ matrix.region }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Update Kubernetes Deployment
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
          DEPLOYMENT_NAME=$(echo "${SERVICE_NAME}" | sed 's/-svc$//')-deployment
          IMAGE=${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gig-space/$SERVICE_NAME:latest
          
          kubectl set image deployment/${DEPLOYMENT_NAME} gig-space-${SERVICE_NAME}=${IMAGE} -n gig-space
          kubectl rollout restart deployment/${DEPLOYMENT_NAME} -n gig-space
