name: Build and Push Docker Images to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - Api_gateway
          - User_svc
          - Payment_svc
          - Chat_svc
          - Search_svc # List all your services
        region: [us-central1] # Region for Artifact Registry

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ matrix.region }}-docker.pkg.dev

    - name: Set up .env file for service
      run: |
        case "${{ matrix.service }}" in
          Api_gateway)
            echo "${{ secrets.API_GATEWAY_CONFIG }}" > ./Api_gateway/.env
            ;;
          User_svc)
            echo "${{ secrets.USER_SVC_CONFIG }}" > ./User_svc/.env
            ;;
          Payment_svc)
            echo "${{ secrets.PAYMENT_SVC_CONFIG }}" > ./Payment_svc/.env
            ;;
          Chat_svc)
            echo "${{ secrets.CHAT_SVC_CONFIG }}" > ./Chat_svc/.env
            ;;
          Search_svc)
            echo "${{ secrets.SEARCH_SVC_CONFIG }}" > ./Search_svc/.env
            ;;
          *)
            echo "No configuration found for ${{ matrix.service }}"
            ;;
        esac

    - name: Build Docker Image
      run: |
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        docker build \
          -t ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME-svc/$SERVICE_NAME:latest \
          ./${{ matrix.service }}

    - name: Push Docker Image to Artifact Registry
      run: |
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        docker push ${{ matrix.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME-svc/$SERVICE_NAME:latest
